# Generated by Django 5.2.7 on 2025-10-14 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_is_delivered_chatmessage_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
