# Generated by Django 5.2.6 on 2025-10-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatuser_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='last_seen',
        ),
    ]
