# Generated by Django 5.2.6 on 2025-10-17 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatuser_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='times',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
