# Generated by Django 5.2.6 on 2025-10-17 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatmessage_timestamp_chatmessage_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='dates',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
