# Generated by Django 5.2.6 on 2025-10-17 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='times',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
