# Generated by Django 5.2.6 on 2025-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chatmessage_dates_remove_chatmessage_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10),
        ),
    ]
