# Generated by Django 5.2.6 on 2025-10-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='is_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
