# Generated by Django 5.2.6 on 2025-10-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatmessage_is_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='is_delivered',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='is_seen',
            new_name='seen_at',
        ),
    ]
