# Generated by Django 5.2.6 on 2025-10-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatuser_is_online_chatuser_last_seen_presence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presence',
        ),
    ]
