# Generated by Django 5.2.6 on 2025-10-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_delete_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='status',
            field=models.CharField(blank=True, default='Hey there! I am using In Chat.', max_length=200),
        ),
    ]
