# Generated by Django 5.2.6 on 2025-10-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chatuser_image_chatuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='password',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='country_code',
            field=models.CharField(default='+91', max_length=10),
        ),
    ]
