# Generated by Django 5.2.6 on 2025-10-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_chatuser_password_chatuser_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
