# Generated by Django 5.2.6 on 2025-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_chatuser_country_code_alter_chatuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='otp_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
