# Generated by Django 5.2.6 on 2025-10-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
