# Generated by Django 5.2.6 on 2025-11-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_chatmessage_attachment_chatmessage_attachment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment_type',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(),
        ),
    ]
