# Generated by Django 5.2.6 on 2025-11-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_chatmessage_attachment_chatmessage_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
